version: '3.8'

services:
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: golfdb
  #     POSTGRES_USER: golfuser
  #     POSTGRES_PASSWORD: golfpass
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./postgres-data:/var/lib/postgresql/data

  #   networks:
  #     - golf-network

  java-service:
    build:
      context: ./golf-api-java
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/golfdb
      SPRING_DATASOURCE_USERNAME: golfuser
      SPRING_DATASOURCE_PASSWORD: golfpass
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8080:8080"
    # depends_on:
    #   - postgres
    networks:
      - golf-network

  # Will be implemented later
  # go-service:
  #   build:
  #     context: ./go-service
  #     dockerfile: Dockerfile
  #   environment:
  #     DB_HOST: postgres
  #     DB_NAME: golfdb
  #     DB_USER: golfuser
  #     DB_PASSWORD: golfpass
  #     REDIS_HOST: redis
  #     REDIS_PORT: 6379
  #   ports:
  #     - "8081:8081"
  #   depends_on:
  #     - redis
  #     - postgres
  #   networks:
  #     - golf-network

  golf-ui:
    build:
      context: ./golf-ui
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - golf-network
    depends_on:
      - java-service

networks:
  golf-network:
    driver: bridge

volumes:
  # postgres-data:
  golf-ui-node-modules: